spring.application.name=ms-laboratorio
server.port=8001
eureka.client.service-url.defaultZone=http://localhost:8000/eureka
eureka.instance.prefer-ip-address=true
logging.level.org.springframework.security=DEBUG
