spring.application.name=ms-distribuidor
server.port=8002
eureka.client.service-url.defaultZone=http://localhost:8000/eureka
eureka.instance.prefer-ip-address=true
jwt.secret=farmacia2025secretkeymuylargaparajwt256bits!
jwt.expiration=36000000
